default: &default
  adapter: postgresql
  encoding: unicode
  pool: 15

development:
  <<: *default
  database: slashernews_development

test:
  <<: *default
  database: slashernews_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>